services:
  traefik-docker-socket-proxy:
    container_name: !reset null
    restart: "no"
  traefik:
    container_name: !reset null
    restart: "no"
    ports: !reset []
    volumes:
      - /home/faviann/repos/homelab-iac/claude-2/stacks/portal/traefik3/appdata/traefik3/config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /home/faviann/repos/homelab-iac/claude-2/stacks/portal/traefik3/appdata/traefik3/config/conf.d:/etc/traefik/conf.d:ro
      - /tmp/portal-traefik-compose-277a57f776bd-8kg4djvd/certificates:/var/traefik/certs:rw
      - /tmp/portal-traefik-compose-277a57f776bd-8kg4djvd/logs:/logs:rw
  redis:
    container_name: !reset null
    restart: "no"
    ports: !reset []
networks:
  shared:
    external: false
